/**
 * Build `lib/client.js` — the half of this plugin that runs in DSH's web app.
 *
 * DSH does not load this as an ES module. It loads it as a self-registering
 * factory that receives a `require` for the host's own copies of React and the
 * slot registry, which is why the bundle is emitted as CJS with those packages
 * external and then wrapped: `require('react')` inside the factory has to reach
 * the host's React, not a second one. Two Reacts in one page is a class of bug
 * nobody should have to debug.
 *
 * The bundle is checked before it is written. Anything the host does not
 * provide must be inlined here, and anything heavy has no business being in a
 * settings page — so a stray import of a graph library fails the build rather
 * than quietly tripling the plugin's size.
 */

import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { build } from 'esbuild'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outfile = join(root, 'lib', 'client.js')
const scratch = join(root, 'lib', '.client.cjs')

/** Exactly what DSH's module table offers. Everything else must be bundled. */
const HOST_PROVIDED = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
]

/**
 * Libraries that would be a mistake in a settings page.
 *
 * The Hub's graph and canvas dependencies are ~550KB together — more than
 * twice this whole plugin — and they are also proprietary. Naming them keeps a
 * future "just import the component" from silently shipping either problem.
 */
const FORBIDDEN = ['cytoscape', 'reactflow', 'iflow-hub-ui']

await build({
  entryPoints: [join(root, 'src', 'client', 'index.jsx')],
  outfile: scratch,
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  external: HOST_PROVIDED,
  minify: true,
  logLevel: 'info',
})

const bundled = readFileSync(scratch, 'utf8')

for (const name of FORBIDDEN) {
  if (bundled.includes(`require("${name}")`) || bundled.includes(`require('${name}')`)) {
    throw new Error(`client bundle requires ${name}, which the host does not provide`)
  }
}

// Every `require` the bundle emits must be answerable by the host's table.
const required = new Set()
for (const match of bundled.matchAll(/require\(["']([^"']+)["']\)/g)) required.add(match[1])
const unknown = [...required].filter((name) => !HOST_PROVIDED.includes(name))
if (unknown.length > 0) {
  throw new Error(
    `client bundle requires modules DSH does not provide: ${unknown.join(', ')}.\n` +
      'Bundle them instead, or use one of: ' + HOST_PROVIDED.join(', '),
  )
}

/**
 * The wrapper DSH expects.
 *
 * `module`/`exports` are declared inside the factory so the CJS bundle has
 * somewhere to write, and the returned object is built explicitly rather than
 * handing back `module.exports` — the host reads `apply` and `inject` off it,
 * and being explicit means a refactor that drops one fails here instead of at
 * load time in someone's browser.
 */
const wrapped = `/**
 * iflow-dsh-plugin — client bundle. Generated by scripts/build-client.mjs.
 * Do not edit by hand.
 */
window.__ModuleLoader__.load({
  id: 'iflow-dsh-plugin',
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${bundled}
    return { inject: module.exports.inject, apply: module.exports.apply };
  },
});
`

writeFileSync(outfile, wrapped, 'utf8')

const kb = (wrapped.length / 1024).toFixed(1)
console.log(`  lib/client.js  ${kb}kb  (host-provided: ${[...required].join(', ') || 'none'})`)

// The intermediate is an artefact of the two-step build, not something to ship.
rmSync(scratch, { force: true })
